### ISSUE TITLE
Onchain Summer Bounty → fxhash Base Mint Ingestor

### ISSUE THREAD

**Issue by christinehall** [floornfts/mobile-minting#5]
* Generate a `MintTemplate` that supports an **fxhash mint on Base** from a URL, such as `https://www.fxhash.xyz/generative/slug/allegro`
* You can test your metadata ingestion against this open mint → ["Allegro" by pixelwank](https://www.fxhash.xyz/generative/slug/allegro)
* The featured image for the collection does not need to show the range of the dynamic outputs — using the collection image is sufficient for this bounty.
* Bounty for this ingestor is 500 USDC, paid upon:
  * Successful approval & merge of the pull request
  * Ingestion of one mint into Mobile Minting ✨

**Comment by chrismaddern** [comment]
This bounty is now closed & rewarded to @yungwkndllc
