### ISSUE TITLE
Onchain Summer Bounty → Foundation Base Mint Integestor

### ISSUE THREAD

**Issue by christinehall** [floornfts/mobile-minting#6]
- Generate a `MintTemplate` that supports an **Foundation mint on Base** from a URL, such as `https://foundation.app/mint/base/0x46d9166c5775BaD333bA09120bE32CD4555C1232`
- You can test your metadata ingestion against this open mint → ["DANCE WITH US" by BEFE](https://foundation.app/mint/base/0x46d9166c5775BaD333bA09120bE32CD4555C1232)
- Bounty for this ingestor is 500 USDC, paid upon:
  - Successful approval & merge of the pull request
  - Ingestion of one mint into Mobile Minting ✨

**Comment by Nith567** [comment]
Actually this mint event has ended unfortunately "https://foundation.app/mint/base/0x46d9166c5775BaD333bA09120bE32CD4555C1232"
