### ISSUE TITLE
Onchain Summer Bounty → Manifold Base Mint Ingestor

### ISSUE THREAD

**Issue by christinehall** [floornfts/mobile-minting#9]
- Generate a `MintTemplate` that supports an **Manifold mint on Base** from a URL, such as `https://app.manifold.xyz/c/Pocus`
- You can test your metadata ingestion against this open mint → ["Hocus Pocus" by @line_art_nfts](https://app.manifold.xyz/c/Pocus)
- Bounty for this ingestor is 500 USDC, paid upon:
  - Successful approval & merge of the pull request
  - Ingestion of one mint into Mobile Minting ✨

**Comment by Nith567** [comment]
Unable to fetch via slug any reason : 
https://apps.api.manifoldxyz.dev/public/instance/data?appId=2537426615&instanceSlug=Pocus

**Comment by Nith567** [comment]
So should I work on mint on base through from an url through id ?

**Comment by chrismaddern** [comment]
Hi @Nith567 - we're excited to see you're interested in contributing to Mobile Minting.

In this case the honest answer is... I don't know.

The goal is to build an ingestor for Manifold mints from the URL, or contract address — the method of doing that is the challenge at hand 😊 

I can help debug based on my insight / some exploring of the API, but ultimately we're looking for you (or anybody who wants to claim the bounty) to propose a working approach.

If you have areas that the team or I can help along the way, let me know!

**Comment by Nith567** [comment]
Yeah i have asked them in their forum, no response yet from their side also the docs & api havent updated since last year. Also could you review this one : https://github.com/floornfts/mobile-minting/pull/18 if not i can could with this url (https://apps.api.manifoldxyz.dev/public/instance/data?appId=2537426615&id=52285680).

**Comment by mawutory** [comment]
I could fetch via Slug by changing the `appId` from `2537426615` to `2522713783`.
